name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: "185.202.236.69"
          USERNAME: "root"
          PORT: "22"
          PASSWORD: "2G456G8iaKBdFf"
        with:
          source: "./target/order-service-0.0.1-SNAPSHOT.jar"
          target: "/tmp/order"

      - name: Restart order service
        uses: appleboy/ssh-action@master
        with:
          HOST: "185.202.236.69"
          USERNAME: "root"
          PORT: "22"
          PASSWORD: "2G456G8iaKBdFf"
          script: |
            mv /tmp/order/target/order-service-0.0.1-SNAPSHOT.jar  /opt/order_service/order-service-0.0.1-SNAPSHOT.jar
            supervisorctl restart all


